import { StyleSheet } from "react-native";
import colors from "../../styles/colors";

export const styles = StyleSheet.create({
  loading: {
    position: "absolute",
    height: 30,
    width: 78,
    left: "40%",
    top: "50%",
    alignItems: "center",
    justifyContent: "center",
  },
  adminContainer: {
    backgroundColor: colors.first,
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 100,
    paddingTop: 15,
  },
  aboutMeSection: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    marginTop: 15,
    backgroundColor: colors.first,
    padding: 10,
  },
  imageSection: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    marginTop: 15,
    backgroundColor: colors.second,
    padding: 10,
  },
  textInput: {
    width: 350,
    height: "auto",
    backgroundColor: "#f7f7f7",
    padding: 8,
    borderRadius: 5,
    fontSize: 14,
    marginVertical: 3,
    marginBottom: 10,
    textAlign: "right",
    color: colors.text,
  },
  btn1: {
    backgroundColor: colors.second,
    width: 150,
    height: 40,
    padding: 0,
    borderRadius: 5,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: 'row',
    gap: 8
  },
  btn: {
    backgroundColor: colors.second,
    width: 90,
    height: 40,
    padding: 0,
    borderRadius: 5,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  photos: {
    display:'flex',
    alignContent: 'space-around',
    justifyContent:'center',
    flexDirection:'row',
    width: '100%',
    gap: 10,
    flexWrap: 'wrap',
    marginBottom: 15,
  },
  itemPhoto: {
    width: 170,
    height: 230,
    shadowColor: "#000",
  },
  TOOverlay: {
    position: "absolute",
    top: 15,
    left: 15,
    height: 25,
    width: 25,
    zIndex: 10,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.first,
    borderRadius: 2,
  }
});
