import { StyleSheet } from "react-native";
import colors from "../../styles/colors";

export const styles = StyleSheet.create({
  button: {
    borderRadius: 7,
    padding: 10,
    width: 110,
    alignItems: "center",
    elevation: 8,
    marginHorizontal: 24,
    height: 40,
  },
  btn: {
    width: "30%",
    height: 40,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 10,
  },
  press: {
    height: 40,
    width: 40,
    display: "flex",
    gap: 20,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  btn1: {
    backgroundColor: colors.first,
    elevation: 8,
    width: 90,
    height: 40,
    padding: 0,
    borderRadius: 5,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  content: {
    display: "flex",
    gap: 20,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingTop: 20,
    height: 170,
    width: "100%",
    // backgroundColor: 'red'
  },
  gap: {
    display: "flex",
    // gap: 20,
    textAlign: 'right',
    direction: "rtl",
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "center",
  },
  down: {
    display: "flex",
    direction: "rtl",
    flexDirection: "row",
    justifyContent: "space-around",
    position: "absolute",
    bottom: 0,
    width: "100%",
    height: 50,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
  },
  buttonOpen: {
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    backgroundColor: colors.first,
  },
});
