import { StyleSheet } from "react-native";
import colors from "../../styles/colors";

export const styles = StyleSheet.create({
    massageStyle: {
      display: 'flex',
      alignItems:'center',
      width: "100%",
      marginTop: 0,
      height: 'auto',
      padding: 12,
      paddingVertical: 30,
      backgroundColor: colors.first,
      gap: 10,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
    },
    QueueButton: {
      backgroundColor: colors.forth,
      borderRadius: 25,
      padding: 4,
      width: 150,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 2, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
      elevation: 2,
      marginVertical: 24,
      height: 40,
    },
    QueueButton1: {
      position: 'absolute',
      bottom: -45,
      backgroundColor: 'white',
      borderRadius: 25,
      padding: 4,
      width: 120,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 2, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
      elevation: 2,
      marginVertical: 24,
      height: 40,
    }
  });